#!/bin/sh
export BIN="$PORTSDIR/bin"

help() {
    echo "$0 [i|r|u|h] [pkg]"
    echo "  i | install [pkg]"
    echo "  r | remove [pkg]"
    echo "  u | upgrade [pkg]"
    echo "  h | help"
}

if [ -n "$2" ]; then
    case "$1" in
        i|install)
            cd "$PORTSDIR/list/$2"
            ./install
            ;; 
        r|remove)
            cd "$PORTSDIR/list/$2"
            ./uninstall
            ;;
        u|upgrade)
            cd "$PORTSDIR/list/$2"
            ./uninstall
            ./install 
            ;;
        help)
            help
            ;; 
        ""|*)
            echo Operation "'$1'" not supported
            ;;
    esac
else
    help
fi
